@protocol = http
@hostname = localhost
@port = 3000
@host = {{protocol}}://{{hostname}}:{{port}}
@baseURL = {{host}}/api
@serviceName = space-crisis

###
# @name getAppResolver
GET {{baseURL}}/app-resolver

###
# @name getAppServiceInfo
GET {{baseURL}}/service/{{serviceName}}

###
# @name createProfile
POST {{baseURL}}/profiles/{{serviceName}}
# Content-Type: application/json

{
  "platform": "dev",
  "uid": "04"
}

###
# @name getTransactionResult
# @prompt txid transaction id to check
GET {{baseURL}}/transactions/{{txid}}

###
# @name getProfileInfo
# @prompt userId user id, eg. dev-01 or google-1xx
GET {{baseURL}}/profiles/{{serviceName}}/{{userId}}

###
# @name invokeUnlockAircraft
# @prompt userId user id, eg. dev-01 or google-1xx
POST {{baseURL}}/profiles/{{serviceName}}/{{userId}}/invoke
# Content-Type: application/json

{
  "method": "unlock-aircraft",
  "params": ["02"]
}

###
# @name invokeSetCurrentAircraft
# @prompt userId user id, eg. dev-01 or google-1xx
# @prompt aircraftId aircraft id
POST {{baseURL}}/profiles/{{serviceName}}/{{userId}}/invoke
# Content-Type: application/json

{
  "method": "set-aircraft",
  "params": ["{{aircraftId}}"]
}

###
# @name invokeSetProperty
# @prompt userId user id, eg. dev-01 or google-1xx
# @prompt value property value
POST {{baseURL}}/profiles/{{serviceName}}/{{userId}}/invoke
# Content-Type: application/json

{
  "method": "set-property",
  "params": ["weapon01", "{{value}}"]
}
